// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// / Default [FirebaseOptions] for use with your Firebase apps.
// /
// / Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJYlH8yvgaLtW9kAJn4bYKtaTxfsv2YyY',
    appId: '1:803830759796:web:90b883c8588b90e18a2c21',
    messagingSenderId: '803830759796',
    projectId: 'travelo-92599',
    authDomain: 'travelo-92599.firebaseapp.com',
    storageBucket: 'travelo-92599.appspot.com',
    measurementId: 'G-TDVN6B3VM7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLW8gPrJkG4SYRdXrWOVCH63QvxXqYB-0',
    appId: '1:803830759796:android:bbfd4687f8e37f418a2c21',
    messagingSenderId: '803830759796',
    projectId: 'travelo-92599',
    storageBucket: 'travelo-92599.appspot.com',
  );
}
